### ISSUE TITLE
Add Travis and scanCode.py support

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-package-template#10]
In addition,  preparation for bringing the code to Apache Software Foundation (ASF) it must be brought into compliance. Meaning...

1) All code must be scanned properly for project conventions.

2) All source code has legal ASF license headers. This includes Python files and the new scanCode.py that will be dropped into openwhisk/tools/build will enable this check by default.

A preliminary scan indicated this repo had the following errors:
  [./openwhisk-package-template/actions/hello_world.js]:
       2: line contains tabs.
       3: line contains tabs.
       4: line contains tabs.
       5: line contains tabs.
       6: file does not end with EOL.

**Comment by dgrove-oss** [comment]
Closing issue as project is being archived.
