### ISSUE TITLE
reference to file that doesn't exist

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk-package-template#3]
.travis.yml reference ./tools/travis/setup.sh
This file doesn't exist in the repo.

Try to split the work into setup.sh and build.sh, leaving .travis.yml very simple and small.

**Comment by csantanapr** [comment]
@tareqmamari take a look at this one

**Comment by tareqmamari** [comment]
Actually, this file is from Openwhisk repo, the only script in `./tools/travis/` is the build.sh which is almost the same as in openwhisk repo (`openwhisk/tools/travis/build.sh`) except that it contains additional steps to activate access to credentials.json, setting up and executing the template test cases.

Should we really split it ?

**Comment by csantanapr** [comment]
My mistake 
Maybe put a comment to be clear

**Comment by csantanapr** [comment]
Never mind I think it's very clear base on the line above my bad. No comment needed it

**Comment by tareqmamari** [comment]
So , I will close it
