### ISSUE TITLE
Concerns on the encryption in Travis CI

### ISSUE THREAD

**Issue by houshengbo** [apache/incubator-openwhisk-package-template#6]
I have got some concerns about the approach how we encrypt the credentials. Travis CI only supports to use one encryption key for one repository, and it is unable to expand to any other repos or even forks. This creates a kind of barrier or difficulty for new contributors to join this project.

For example, other contributors have to maintain their own encryption keys in their forks, if they want to set up the travis ci for their forks. Otherwise, the test cases will fail.

Other contributors have to maintain their own .enc files, if they are using different keys from the master repo. Otherwise, the test cases will fail.

Other contributors need to ask for the encryption key, if they try to keep .enc file consistent with the master repo. Who is keeping the encryption key? What permission do developers need to access this encryption key? Imagine hundreds or thousands of people would like to contribute. It is a lot of burden.

...

All the above situations have brought negative user or developer experience, which is not compliant with the open source mindset, easy to use, easy to contribute, easy to join, etc.

I have tried to find out a better way to encrypt the credentials in travis ci, but did not succeed.
I am not sure if we should follow the approach of encrypting files.

**Comment by houshengbo** [comment]
@Tareq Al-Maamari 
@daisy-ycguo @lzbj @csantanapr @rabbah @jasonpet 
Folks, I have got concerns on the encryption so far.

**Comment by mrutkows** [comment]
Remember, most packages will not need to come with their own keys (as they are optional or "as is"; that is, only packages that we wish to incorporate into automated testing (CD/CI) need to have keys (credentials) and if they in turn are protected by a single repo. key that should be fine for the foreseeable future.  For the majority of new packages, the user should be expected to "bring their own keys" (credentials) and how to use them should be documented.

**Comment by houshengbo** [comment]
@mrutkows As long as there are some tests related to keys brought into Travis CI, even only one, we will running into the issues I mentioned above. In my opinion, if travis ci is unable not provide any better solution to encrypt keys, I tend not to adopt the current approach, unless private actions have their own repos. Take openwhisk-catalog for example, if some actions need keys to authenticate the service and they are triggered on in the travis ci, we will running into a chaos of managing encryption keys among all the forks by many developers. Hundreds or even thousands. 

Each time a new developer comes in, they have to get a key to make sure all the tests passed in their environment, which does not sound good for an open source project.

**Comment by csantanapr** [comment]
@houshengbo I'm aware of the situation. I'm on favor on moving forward on using Travis CI encryption feature for our repos.

The are more benefits than downsize.

encryption key will be kept private to only those that need them, no different than other open source organizations (like Apache PMC)

The easiest way for a new contributor is to send a PR, and their commits automatically get tested, no barrier there.

Next level is for contributor if they want to test locally to get their own credentials.

Don't see a lot of contributors to an existing repo using travis encryption maintaining their fork with their own Travis Builds, if they do then it will be for cases where they have their own package using a service that their package depends on.

For sharing encrypted files and sync, each repo should only have the unique keys that it needs.

**Comment by tareqmamari** [comment]
@houshengbo: The approach you mentioned is normal to avoid secrets leaking. Travis create secured environment variables (the IV and Key) during the encryption process. These secured env vars can not be exposed by pull requests sent from a fork of the upstream repository. The only way to access them is within the repo itself (PR from the repo itself). Again, all of these complexities to secure the encrypted data. The other alternatives through travis (i.e. Encrypted env vars) are also protected in the same way.

In general, each contributor needs to provide their own keys, the encryption is only for travis. We still need to figure out another alternative for Pull Requests to use contributors' keys.

**Comment by dgrove-oss** [comment]
Closing issue as project is being archived.
