### ISSUE TITLE
Travis build fails

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-package-template#9]
It appears that the method for finding the whisk.properties file and that assumed environment variables (i.e., WSK_CLI primarily) are not found or present.

<img width="1040" alt="screen shot 2017-01-02 at 1 52 23 pm" src="https://cloud.githubusercontent.com/assets/7816715/21595386/05e3c2c0-d0f3-11e6-862c-881531dbf03a.png">

**Comment by mrutkows** [comment]
If this fails, so will the RSS feed package I assume?

**Comment by rabbah** [comment]
what is the `APIHOST` key in the screenshot?

**Comment by mrutkows** [comment]
Was looking at why a PR fixing simple indentation failed: https://github.com/openwhisk/openwhisk-package-template/pull/8

**Comment by mrutkows** [comment]
The APIHOST is an input to the install.sh script and passed to the CLI: 
[https://github.com/openwhisk/openwhisk-package-template/blob/master/install.sh](https://github.com/openwhisk/openwhisk-package-template/blob/master/install.sh)

specifically here: 
[18] $WSK_CLI --apihost $APIHOST package update --auth $AUTH --shared yes  packageTemplate \
    -a description "Openwhisk Package Template" \
-a parameters '[{"name":"apiKey","required":true,"bindTime":true,"description":"Watson ...

Of course, this package has not been updated/touched in 6 months (June) so likely many things have changed that need to be looked at.

**Comment by rabbah** [comment]
From the screen shot the APIHOST is not set to a host but looks like a service key (should this key appear in the logs?).

**Comment by dgrove-oss** [comment]
Closing issue as project is being archived.
